- README.md
This PR fixes small typos on the README
> Fix typo on kubernetes.yaml

- Gemfile
- Rakefile
- metadata.json
Request to review the small changes on the files to fix the jenkins pipeline for the following jobs(merge,static,unit)
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/__experimental%20automatic/job/experimental_auto_puppetlabs-kubernetes_init-merge_master/
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/__experimental%20automatic/job/experimental_auto_puppetlabs-kubernetes_static-module_master/
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/__experimental%20automatic/job/experimental_auto_puppetlabs-kubernetes_unit-module_master/
> (metadata dependencies options)

- CHANGELOG.md
- manifests/cluster_roles.pp
- manifests/config.pp
- manifests/init.pp
- manifests/kube_addons.pp
- manifests/params.pp
- metadata.json
- spec/classes/cluster_roles_spec.rb
- spec/classes/config_spec.rb
- templates/clusterRoleBinding.yaml.erb
- templates/kube-apiserver.yaml.erb
- templates/kubelet.conf.erb
- templates/secrets/bootstraptoken.yaml.erb
This PR adds support for Kubernetes 1.8.x
> Kube 1.8.3 support

- manifests/kube_addons.pp
- spec/classes/kube_addons_spec.rb
Request to review small changes for dashboard
Deploying master version for 1.8 version and above and deploying v1.6.3 for version 1.6 & 1.7
> (dashboard deploy for each version)

- spec/acceptance/nodesets/pooler/centos7.yml
- spec/spec_helper_acceptance.rb
Request to review the changes to run on centos box for vagrant and vmpooler. Exected on both and they ran successfully.
> (CLOUD-1614) Fix acceptance tests to run on centos

- README.md
Previous to this PR, the README's setup instructions instructed users to either
install all of the dependencies for the kubetool in order to run it, or to
build a Docker image using the Dockerfile in this repository. 
This PR instructs the users to just use `docker run` with the new
puppet/kubetool image in Docker Hub.
> Update README to use new puppet/kubetool image

- .fixtures.yml
- README.md
- manifests/init.pp
- manifests/params.pp
- manifests/repos.pp
- metadata.json
- spec/classes/repos_spec.rb
This PR removes the dependency for EPEL
> removing epel from the module

- .fixtures.yml
- Gemfile
- Rakefile
- manifests/init.pp
- manifests/service.pp
- metadata.json
- spec/spec_helper_acceptance.rb
Request to review the changes to add i18n gems to the module
https://confluence.puppetlabs.com/display/systemsEngineering/How+to+Prepare+Your+Module+for+Translation
> (i18n Gem update for k8)

- README.md
- manifests/init.pp
- manifests/kube_addons.pp
- manifests/params.pp
- spec/classes/kube_addons_spec.rb
A PR to tag the master node correctly and stop pods being scheduled on the master node.
> Cloud 1595

- README.md
adding test line to readme to test if automated build is kicked off.
> (automated build)

- README.md
I added a test line to readme for automated build stuff I am just removing that in this PR.
> (maint)undoing change made when testing

- manifests/packages.pp
- spec/classes/packages_spec.rb
Reverts puppetlabs/puppetlabs-kubernetes#53 Reverting to fix this another way
> Revert "(CLOUD-1640) Remove package resource for kubernetes-cni"

- manifests/params.pp
Fix to stop RHEL family downgrading cni
> Fix to stop RHEL family downgrading cni

- .travis.yml
- manifests/kube_addons.pp
Request to review the fix for lint warning
bundle exec puppet-lint --no-autoloader_layout-check manifests
> (fixing lint warning for k8)

- spec/acceptance/kubernetes_spec.rb
- spec/spec_helper_acceptance.rb
- tooling/kube_tool/other_params.rb
Addresses concerns in issue #62
> fixes weave URL in kube_tool and uses default IP range

- README.md
- manifests/init.pp
- manifests/params.pp
- spec/classes/packages_spec.rb
This PR updates the default values to kube = 1.9.2 and cni = 0.6.0
> Update default values

- README.md
- manifests/init.pp
- manifests/kube_addons.pp
- manifests/params.pp
- spec/classes/kube_addons_spec.rb
> Cloud 1731

- manifests/repos.pp
- rakelib/acceptance.rake
- spec/acceptance/nodesets/pooler/rhel7.yml
- spec/spec_helper_acceptance.rb
> fix for RHEL repo

- manifests/repos.pp
- spec/classes/repos_spec.rb
Previous key expired on 2018-04-02
> Update gpg key fingerprint used by K8s Ubuntu repo

- CHANGELOG.md
- metadata.json
> bumping version in metadata.json and updating changelog

- README.md
README.md was still pointing at an old version.
> README.md - use current version number

- README.md
- manifests/params.pp
changes the default runtime to docker
> updating default runtime

- README.md
the .env file is in the root folder and not the tooling folder ;)
> fix wrong folder name

- metadata.json
- spec/spec_helper_acceptance.rb
> adding in puppet wget module

- manifests/init.pp
- manifests/kube_addons.pp
- manifests/params.pp
- spec/classes/kube_addons_spec.rb
- tooling/kube_tool/other_params.rb
updates calico url in kubetool
fixes issue #118
> adds in param to configure rbac for calico

- manifests/service.pp
- templates/20-cloud.conf.erb
- templates/config.yaml.erb
Ensure a new kubelet systemd configuration is added to configure cloud provider arguments when cloud provider is enabled.
Also fixed a lot of white space issues in this file.
> Fixed missing cloud provider arguments for kubelet

- templates/config.yaml.erb
Hyphen made arguments misplaced array elements.
> Cleaning up apiServerExtraArgs

- manifests/cluster_roles.pp
Fixes an error with the number of arguments being passed to the flatten function
> Flatten fix

- .rubocop.yml
- .sync.yml
- .travis.yml
- Gemfile
- metadata.json
- spec/spec_helper.rb
Update .sync.yml to remove duplicate dependency declarations
and switched to using the puppet-module-gems.
Also includes subsequent PDK template changes.
> (maint) Updated .sync.yml

- README.md
> (CLOUD 2195) Readme update.

- README.md
- manifests/config.pp
- manifests/init.pp
- spec/classes/config_spec.rb
- spec/classes/service_spec.rb
- templates/config-alpha3.yaml.erb
Fixes https://github.com/puppetlabs/puppetlabs-kubernetes/issues/197
> Add support for configuring kubeletExtraArgs in v1alpha3 config.

- manifests/init.pp
- templates/config-alpha3.yaml.erb
> fixing alignment in init.pp and problem with variables in config3 

- manifests/packages.pp
> adding in logic for managing kmod alternatively

- manifests/service.pp
- spec/classes/service_spec.rb
> enable kubelet service

- manifests/repos.pp
(facepalm) Stupid swap of repos, my bad. Please merge.
> Fix CentOS repos

- spec/spec_helper_acceptance.rb
- tooling/Dockerfile
> Update go version

- manifests/config.pp
> restricts access to kube dirs to root only

- manifests/init.pp
- manifests/kube_addons.pp
This is needed in environments with no direct Internet access
> introduce kubernetes_dashboard_url param

- spec/spec_helper_acceptance.rb
> MODULES-9171 fix failures on centos

- manifests/config/kubeadm.pp
- manifests/init.pp
- spec/classes/config/kubeadm_spec.rb
- templates/v1beta1/config_kubeadm.yaml.erb
> make proxy mode configurable

- README.md
> MODULES-9225 Add module contribution guide

- manifests/config/kubeadm.pp
- manifests/config/worker.pp
Addresses https://github.com/puppetlabs/puppetlabs-kubernetes/issues/305
> Modify config_version to kubernetes_version mapping. Pre-req to supporting Kube 1.15

- CHANGELOG.md
- metadata.json
> (MODULES-9550) - 5.0.0 Release Prep

- manifests/config/kubeadm.pp
- manifests/init.pp
- templates/v1alpha3/config_kubeadm.yaml.erb
- templates/v1beta1/config_kubeadm.yaml.erb
Fixes issue https://github.com/puppetlabs/puppetlabs-kubernetes/issues/277
> Expose ttl duration parameter

- metadata.json
Needed to update the puppetlabs-apt dependency.
Tested without errors
> update puppetlabs-apt dependency

- manifests/init.pp
- manifests/packages.pp
- spec/classes/packages_spec.rb
- templates/docker/daemon_debian.json.erb
- templates/docker/daemon_redhat.json.erb
Fixes https://github.com/puppetlabs/puppetlabs-kubernetes/issues/357
> Add support for managing Docker logging max-file and max-size settings.

- manifests/config/kubeadm.pp
- spec/classes/config/kubeadm_spec.rb
Configure extra_volumes when cloud_provider is set and cloud_config is not. Fixes #301
> Configure extra_volumes when cloud_provider is set and cloud_config is not. Fixes #301

- .travis.yml
- provision.yaml
- spec/spec_helper_acceptance_local.rb
> (maint) FM-8788 testfix for redhat and centos

- .sync.yml
- .travis.yml
- Gemfile
- metadata.json
Updated .sync.yaml and ran pdk update .
> (MODULES-10352) Fix sync.yaml file

- .github/workflows/release.yml
- .sync.yml
- .travis.yml
- Rakefile
- metadata.json
- spec/spec_helper.rb
"(IAC-365) updating tokens and dataset for honeycomb"
pdk version: `1.16.0`
> (IAC-365) updating tokens and dataset for honeycomb

- README.md
> Improve acceptance test documentation

- .github/workflows/release.yml
- .github/workflows/weekly.yml
- Gemfile
Add dependency gems to development group
pdk version: `1.17.0`
> pdksync - Add dependency gems to development group

- manifests/config/kubeadm.pp
- manifests/init.pp
- manifests/kube_addons.pp
- templates/v1beta1/config_kubeadm.yaml.erb
- templates/v1beta2/config_kubeadm.yaml.erb
Add two features:
1. Options DnsDomain
> Add option to set the dns domain in kubernetes cluster

- templates/v1beta1/config_kubeadm.yaml.erb
Fixing https://github.com/puppetlabs/puppetlabs-kubernetes/issues/406.
> Remove invalid field "max" from conntrack spec

- manifests/init.pp
- manifests/repos.pp
Fixes issue: https://github.com/puppetlabs/puppetlabs-kubernetes/issues/402
> Update default yum repositories for docker

- manifests/init.pp
- manifests/kube_addons.pp
- manifests/packages.pp
- spec/classes/packages_spec.rb
- templates/docker_apt_package_pins.erb
- templates/kubernetes_apt_package_pins.erb
This solves #365
Remove swapspace entries from /etc/fstab.
> Disable swap permanently

- Gemfile
- spec/acceptance/kubernetes_spec.rb
- spec/spec_helper_acceptance_local.rb
> (IAC-1062) fix tests

- metadata.json
(feat) - Add support for Puppet 7
pdk version: `1.18.1`
> pdksync - (feat) - Add support for puppet 7

- REFERENCE.md
- manifests/config/kubeadm.pp
- manifests/init.pp
- templates/etcd/etcd.erb
- templates/etcd/etcd.service.erb
The goal of the PR is to be able to specifiy the --max-request-bytes option for etcd managed by the module.
> add etc max-request-bytes option

- README.md
Hey @carabasdaniel  Hope you are doing well. Thank you for your support in resolving the Hiera data fetch issue. Have updated the Readme. Below is the summary of the changes. Let me know if changes are required.
1. Corrected few Markdown Linting Issues
2. Added information about Hiera YAML Data lookup
3. Added information about installing a updated Kubernetes version.
Fixes https://github.com/puppetlabs/puppetlabs-kubernetes/issues/491, https://github.com/puppetlabs/puppetlabs-kubernetes/issues/476, https://github.com/puppetlabs/puppetlabs-kubernetes/issues/381
> Added information about Hiera YAML Lookup; installing a updated version.

- .fixtures.yml
- .github/workflows/auto_release.yml
- .github/workflows/integration_test.yml
- .github/workflows/nightly.yml
- .sync.yml
- Rakefile
- metadata.json
- plans/provision_cluster.pp
- plans/provision_gcp.pp
- plans/puppetserver_setup.pp
- spec/acceptance/integration_kubernetes_spec.rb
- spec/acceptance/kubernetes_spec.rb
- spec/spec_helper_acceptance_local.rb
Request for a review
Added plans for provisioning and puppetserver setup for cloud ci
Modified spec_helper_acceptance_local for puppet server/agents configuration and replaced with docker tool to generate the certs
Added tests to verify controller/worker.
Added new tags for testing integration in Rakefile
Added tags to the tests
> (maint) port tests to cloud ci

- .github/workflows/auto_release.yml
- .github/workflows/integration_test.yml
- Gemfile
- metadata.json
- spec/spec_helper_acceptance_local.rb
PDK Update for auto release prep workflow
pdk version: `1.18.1`
> pdksync - PDK Update for auto release prep workflow

- lib/puppet/parser/functions/kubeadm_init_flags.rb
- manifests/cluster_roles.pp
- manifests/init.pp
- manifests/kubeadm_init.pp
Skip some phases, for example, add-ons
> Add kubeadm skip-phases option

- README.md
Fix https://github.com/puppetlabs/puppetlabs-kubernetes/issues/424
> Add ttl_duration to README

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .fixtures.yml
- .github/workflows/auto_release.yml
- .github/workflows/spec.yml
- Gemfile
- Rakefile
- metadata.json
pdksync_heads/main-0-gf3911d3
pdk version: `2.3.0`
> pdksync - pdksync_heads/main-0-gf3911d3

- manifests/config/kubeadm.pp
> fix: anchor regex for determining config_version

- manifests/kube_addons.pp
- manifests/kubeadm_init.pp
- manifests/kubeadm_join.pp
- manifests/packages.pp
- manifests/service.pp
- manifests/wait_for_default_sa.pp
- spec/defines/kubeadm_init_spec.rb
- spec/defines/kubeadm_join_spec.rb
- spec/defines/wait_for_default_sa_spec.rb
Prior to this commit some commands in our manifest classes would not be up to our code standards.
This commit aims to sanitise our code according to our teams best practices.
> Hardening manifest classes

- manifests/config/kubeadm.pp
- manifests/init.pp
- spec/classes/config/kubeadm_spec.rb
- templates/etcd/etcd.erb
- templates/etcd/etcd.service.erb
Signed-off-by: Miroslav Svoboda <email@svobodamiroslav.cz>
> etcd data dir path configurable by hiera

- Gemfile
- manifests/config/kubeadm.pp
- metadata.json
(MAINT) - Remove deprecated has_key
pdk version: `2.6.1`
> pdksync - (MAINT) - Remove deprecated has_key

- .puppet-lint.rc
- .sync.yml
- Rakefile
- manifests/cluster_roles.pp
- manifests/config/kubeadm.pp
- manifests/config/worker.pp
- manifests/init.pp
- manifests/kube_addons.pp
- manifests/kubeadm_init.pp
- manifests/kubeadm_join.pp
- manifests/packages.pp
- manifests/repos.pp
- manifests/service.pp
- manifests/wait_for_default_sa.pp
- plans/provision_cluster.pp
Code now compliant with rules regarding:
parameter documentation
file ensure check
non-enclose variables
> (CONT-358) Syntax update

- metadata.json
Fixing CI pipeline.
- N/A
Mention any related issues or pull requests.
> (CONT-1211) - Fixing CI pipeline

- metadata.json
Update kmod dependency
- N/A
- N/A
> (MAINT) - Update kmod dependency

- .rubocop.yml
- Gemfile
- metadata.json
- spec/spec_helper.rb
> (CAT-1608) - PDK update

- .rubocop.yml
- .vscode/extensions.json
- Gemfile
- Rakefile
- metadata.json
Fixing the duplicate gem in diff group with diff version.
> (CAT-1696) - Fixing pipeline

- README.md
Update README.md to our current certification version of kubernetes
> Update README.md to our current certification version of kubernetes

- manifests/init.pp
Trivial fix for wrong default in comment
> Fix container_runtime default in comment

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
> MODULES-11577 chore(ruby): upgrade Ruby from 2.7 to 3.1
