templates/addons/kube-proxy.yaml.erb

correct kube-proxy template to use bootstrap_controller_ip rather than a hard-coded address

Remove hard-coded address from proxy configmap template

---

spec/acceptance/kubernetes_spec.rb
spec/spec_helper_acceptance.rb

small changes for fixing the errors on jenkins pipeline

k8_jenkins

---

manifests/packages.pp
spec/classes/packages_spec.rb

Prior to this commit, kubernetes-cni was installed as a separate
package resource.  Regardless of the version specified, yum would
detect the kubelet prerequisite, which would automatically pull the
latest version.  Since we install kubelet just a few lines later,
and that installation will automatically pull the needed version
of kubernetes-cni, this package resource appears to not be needed,
and causes the incorrect version to get installed.
Removing it resolved the errors since the needed dependencies will be
pulled in when kubelet is installed.
would automatically pull in the most recent version

(CLOUD-1640) Remove package resource for kubernetes-cni

---

manifests/kube_addons.pp

Prior to this commit, puppet agent runs on a controller would
fail because there is a relative path used in the assign master role
and taint master node execs.  These paths are present in the
resource default, but that is contained within the bootstrap-controller
conditional and thus not available for controllers.  This patch moves
the resource default above the conditional so it is present for both.

(CLOUD-1701) Add path attribute to execs in kube_addons

---

manifests/kube_addons.pp

fixes #60 
Where a node has a FQDN, this will allow the role/taint to be applied correctly. Where the shortname and FQDN are the same, this will also work without issue.

changing taint and label to fqdn

---

tooling/Dockerfile

This fix the issue that cfssl trust has been removed from there vendor path

fix for cfssl trust no longer being in the vendor path

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/cluster_roles_spec.rb
spec/classes/config_spec.rb
spec/classes/kube_addons_spec.rb
spec/classes/packages_spec.rb
spec/classes/service_spec.rb
templates/kube-apiserver.yaml.erb

In some environments, additional volumes are rqeuired for the apiserver
to function as expected. For example, on CentOS 7 controller nodes, the
host CA certificate bundles mounted at /etc/ssl/certs are broken since
this directory contains symlinks pointing to an unmounted path.
In other environments this may be used to provision a specific directory
which is referred to by other apiserver arugments, e.g.
"--oidc-ca-file".

Allow mounting extra volumes to apiserver pod

---

manifests/cluster_roles.pp

Fix for failing idempotency on worker nodes, since these do not have the admin.conf:
```
Debug: Exec[kubeadm join](provider=posix): Executing check 'kubectl get nodes | grep ics106067240'
Debug: Executing: 'kubectl get nodes | grep ics106067240'
Debug: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_join[ics106067240]/Exec[kubeadm join]/unless: The connection to the server localhost:8080 was refused - did you specify the right host or port?
Debug: Exec[kubeadm join](provider=posix): Executing 'kubeadm join '146.106.67.212:6443' --discovery-token-ca-cert-hash 'sha256:xxx' --token 'xxx''
Debug: Executing: 'kubeadm join '146.106.67.212:6443' --discovery-token-ca-cert-hash 'sha256:xxx' --token 'xxx''
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_join[ics10606724 …
```

Fix for failing idempotency on worker nodes

---

templates/config.yaml.erb

There was still an issue when you have a 2nd SAN it is indenting differently from the first SAN.

Fixed indenting issue when configuring multiple extra apiserver cert SANs

---

README.md
manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/config_spec.rb
spec/classes/service_spec.rb
templates/config.yaml.erb

Provide an extension point `kubeadm_extra_config` to allow configuration
of all kubeadm config properties not otherwise explicitly exposed.

Allow arbitrary extra kubeadm config.yaml snippets

---

manifests/init.pp
manifests/packages.pp
manifests/params.pp
manifests/repos.pp
manifests/service.pp
spec/classes/packages_spec.rb
spec/classes/repos_spec.rb
spec/classes/service_spec.rb

Some people might want to use other modules or custom profiles for
configuring and installing Docker.
Using a feature flag to enable/disable the management of Docker makes the
above possible.

 Add feature flag for managing Docker repositories and packages

---

README.md

Readme updates include:
- Removed installation section as this is described when published to the Forge.
- The module is now PDK compliant, so I have added the "Validating and unit testing the module" section.
- Updated the Limitations section: updated Ubuntu to 18.04 and added Ruby 2.3.0 or higher.  
- Reorganized parameters and double-checked entries against those in the init.pp. 
- Minor edits elsewhere in the Readme.

(CLOUD-2054) Readme updates.

---

README.md
manifests/config.pp
manifests/init.pp
manifests/packages.pp
manifests/params.pp
manifests/service.pp
spec/classes/config_spec.rb
spec/classes/packages_spec.rb
spec/classes/service_spec.rb

In some cases a custom Etcd installation or running Etcd as a deployment
in the Kubernetes cluster itself is desired.
This commit adds a feature flag for enabling/disable the installation of
an external Etcd via this module.

Add feature flag for managing Etcd

---

Gemfile

This PR is to pin the puppet version to 5.5.6 until puppet 6 support is added. The reason for pinning is that  the latest puppet version is being pulled and is breaking ci as we havent added support yet.

(Maint)Pinning puppet version until puppet 6 support added.

---

lib/puppet/parser/functions/kubeadm_init_flags.rb
lib/puppet/parser/functions/kubeadm_join_flags.rb

This commit is needed to support Puppet 6, where we fixed this bug:
https://tickets.puppetlabs.com/browse/PUP-9112
We need to test for both an undef vaule (backwards compatible) and nil
(in Puppet 6 and beyond)

(maint) Fix function nil / undef conditionals for Puppet6

---

metadata.json

MR #141 implements the usage of `to_yaml` which is introduced in stdlib version [4.20.0](https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/CHANGELOG.md#supported-release-4200).
However the current metadata.json requires version 4.19.0.

Updated stdlib version requirement to >= 4.20

---

README.md
manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/config_spec.rb
spec/classes/service_spec.rb
templates/config-alpha1.yaml.erb
templates/config-alpha3.yaml.erb

Support is added for both the alpha1 and alpha3 config.yaml formats.
Before the alpha3 format, kubelet configuration could be added via
kubeadm_extra_config.  However, that doesn't work with the alpha3
format since kubelet configuration is passed via a separate YAML
document with kind == KubeletConfiguration:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3#hdr-Kubeadm_init_configuration_types

Support customized kubelet configuration.

---

manifests/packages.pp
spec/spec_helper_acceptance.rb

Prevents failures where sysctl was being run in the catalog before the kernel module was loaded.

adding in ordering for sysctl to present failures

---

templates/config-alpha3.yaml.erb

section of the config-alpha3 template where kubeadm expects it.

Move kubernetesVersion into ClusterConfiguration

---

manifests/config.pp
manifests/service.pp
spec/classes/config_spec.rb
spec/classes/service_spec.rb
templates/20-cloud.conf.erb
templates/config-alpha3.yaml.erb

As implemented today the command line parameters will be set in {{kubeadm-flags.env}} but immediately overwritten by a blank value from `/etc/sysconfig/kubelet`
```
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
EnvironmentFile=-/etc/sysconfig/kubelet
```
In AWS case if the node is registered without the cloud provider it doesn't get it's ID looked up from metadata, and it has to be destroyed and booted again.
The following set of fixes are working here. It retains the old behavior for versions prior to 1.12, but uses kubelet configmap for cloud configuration for 1.12+ as recommended
Also changes:
Only add config file parameter if it has a value
--most cloud providers don't use one and it will fail startup if one is specified but missing
Add spec tests to ensure cloud is configured …

Fix multiple errors in cloud configuration

---

manifests/init.pp
manifests/repos.pp

There's no convenient or simple way to ensure lsb-core is installed on RHEL systems, and in general evaluating code for a different OS just propagates failures unrelated to the using OS. This patch defers the default value analysis until the point of usage, which succeeds for all practical purposes and ducks this issue.
fixes #218

Defer os-specific default value test to avoid fact availability issues

---

manifests/init.pp
manifests/kube_addons.pp
spec/classes/kube_addons_spec.rb

It appears they want people to install from specific branches rather than master. I can't imagine why ;-)
This adds a dashboard version parameter which is the branch name to use, so one can select an alternative branch if they want. Tests were updated too.

Dashboard no longer has deploy YAML on master branch

---

manifests/service.pp
spec/classes/service_spec.rb

This solves the following problems on RedHat:
```
Dec 5 12:42:03 kubelet: E1205 12:42:03.527763 23059 summary.go:92] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
Dec 5 12:42:03 kubelet: E1205 12:42:03.527796 23059 summary.go:92] Failed to get system container stats for "/system.slice/docker.service": failed to get cgroup stats for "/system.slice/docker.service": failed to get container info for "/system.slice/docker.service": unknown container "/system.slice/docker.service"
Dec 5 12:42:03 kubelet: W1205 12:42:03.527852 23059 helpers.go:847] eviction manager: no observation found for …
```

Fix systemd cpu/memory problems on RedHat

---

manifests/kube_addons.pp

If a user deletes the flannel or the weave daemonset, a re-puppet should
add flannel back to the cluster. Because of the creates statement, one
would have to `rm -rf /etc/cni/net.d` and then re-puppet to get flannel
back. This is not intuitive behavor. This patch will re-apply flannel if
no flannel or weave daemonset exists.

Fix cni network provider

---

templates/config-alpha3.yaml.erb

nodeName isn't valid in v1alpha3 cluster configuration https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3#ClusterConfiguration
This patch removes the JSON formatting error.

Fix alpha3 template

---

templates/config-alpha3.yaml.erb

This was in the alpha1 config, but it is missing in the alpha3 config.

Honor overridden service address range in alpha3 config.

---

manifests/config.pp
spec/classes/config_spec.rb
templates/config-alpha3.yaml.erb

If a cloud configuration is used, it must be mounted in these pods as of 1.11
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#new-deprecations
Failure to do so causes these two pods to startFail and the cluster never comes up.
https://github.com/kubernetes/kubernetes/issues/57718

Mount cloud configuration on ApiServer and ControllerManager pods

---

manifests/init.pp
manifests/repos.pp

Without this, a puppet4 agent which doesn't appear to have newer facts will fail with the
error "Evaluation Error: Operator '[]' is not applicable to an Undef Value".  After this change, evaluation works and the override values supplied to the model can take effect.

Use fact method to more gracefully handle missing facts

---

manifests/cluster_roles.pp
manifests/config.pp
manifests/config/worker.pp
manifests/init.pp
manifests/kubeadm_init.pp
manifests/kubeadm_join.pp
spec/classes/config/worker_spec.rb
spec/classes/config_spec.rb
spec/classes/init_spec.rb
spec/defines/kubeadm_init_spec.rb
spec/defines/kubeadm_join_spec.rb
templates/config-alpha3.yaml.erb
templates/v1alpha3/config_worker.yaml.erb

This resolves the same cloud_provider problem for workers as the previous patch.
It also does some strategic structure for the new config-file-oriented world,
which will hopefully make it easier to obsolete older versions with less pain.
I wouldn't merge this yet, I don't think it's been tested all the ways it needs to be. We need some eyeballs on this in different environments.

Build config file for worker nodes too

---

manifests/cluster_roles.pp
manifests/init.pp
manifests/kube_addons.pp
manifests/kubeadm_init.pp
manifests/kubeadm_join.pp
manifests/packages.pp
manifests/wait_for_default_sa.pp
spec/classes/kube_addons_spec.rb
spec/defines/kubeadm_init_spec.rb
spec/defines/kubeadm_join_spec.rb
spec/defines/wait_for_default_sa_spec.rb

This is a workaround for a known race condition where you can try to add a Pod before the cluster has created the default serviceaccount https://github.com/kubernetes/kubernetes/issues/66689
```
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[kube-master]/Exec[kubeadm init]/returns: executed successfully
Notice: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]/returns: serviceaccount/weave-net created
Notice: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]/returns: clusterrole.rbac.authorization.k8s.io/weave-net created
Notice: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]/returns: clusterrolebinding.rbac.authorization.k8s.io/weave-net created
Notice: …
```

Workaround race condition on default sa creation

---

manifests/kube_addons.pp
spec/fixtures/hiera/required_values.yaml

I've come around on this, as I've started to experience a lot more need for passing shell metacharacters in the URLs. I believe using stdlib's `shell_escape` is the best, most practical fix.
resolves #232

Safe command lines for CNI network installs

---

manifests/config/kubeadm.pp
manifests/config/worker.pp
manifests/init.pp
spec/classes/config/kubeadm_spec.rb
spec/classes/config/worker_spec.rb
templates/v1alpha3/config_kubeadm.yaml.erb
templates/v1alpha3/config_worker.yaml.erb

```
$  kubelet --help |grep cgroup
--cgroup-driver string
Driver that the kubelet uses to manipulate cgroups on the host.
Possible values: 'cgroupfs', 'systemd' (default "cgroupfs")
(DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag.
See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)
```
This PR also includes major refactoring to make YAML template build tests less prescriptive and less likely to fail due to minor changes that aren't actual failures.

Store cgroup driver in kubeadm configuration file for kubernetes 1.12+

---

manifests/cluster_roles.pp
manifests/init.pp
manifests/kubeadm_init.pp
manifests/kubeadm_join.pp
manifests/wait_for_default_sa.pp

This is an alternative implementation of #257 which moves the kubectl environment out to the main class for later reuse. Setting that environment within cluster roles means that it's only available in routines called by cluster roles, and I think this is a general-purpose need.

Make kubectl environment available in main class

---

manifests/config/kubeadm.pp

This fixes an issue when a user is not using the cloud provider, and using kubeadm_extra_config to define controllerManagerExtraArgs and apiServerExtraVolumes the fields are defined twice making the yaml invalid. 
The variable being removed are only used inside the cloudprovider block, and can otherwise be defined by the users in the other fields available. They are not parameters usable by users in a manifest.

removes redundant variables in the case of not using the cloud provider

---

README.md
manifests/config/kubeadm.pp
manifests/init.pp
templates/etcd/etcd.service.erb

This PR makes the etcd instance name configurable.
It was always set to be the hostname before. We need it to be the FQDN instead.

Etcd hostname variable

---

manifests/cluster_roles.pp
manifests/init.pp
manifests/kube_addons.pp
manifests/kubeadm_init.pp
spec/acceptance/kubernetes_spec.rb
spec/spec_helper_acceptance.rb
templates/v1beta1/config_kubeadm.yaml.erb

Request to review the following changes
- env settings specified for wait_for_default_sa & kube_addons.pp to set the env correctly
- upgraded the k8 version and go version on spec_helper_acceptance tests
- Updated the k8 version in the testcase
- Added the variable ignore_preflight_errors to init.pp
- updated the default value for etcd version
- coredns is default dns (hence modified the testcase for 1.13.5)
**K8 Acceptance test Results**
`he Kubernetes module
clean up before each test
kubernetes class
it should install the module and run
localhost $ scp /var/folders/4v/p90k7dqd65348jw6l6xrppdw0000gq/T/beaker20190425-35875-1puinxd ubuntu-1604-master:/tmp/apply_manifest.pp.dmlBKw {:ignore => }
should run
should install kubectl
should install kube-dns
application deployment
can deploy an …

MODULES-8947 fixing bugs and tests

---

templates/v1alpha3/config_worker.yaml.erb
templates/v1beta1/config_worker.yaml.erb

Currently produces this:
```
Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_join/Exec[kubeadm join]/returns: error converting YAML to JSON: yaml: line 4: found character that cannot start any token
```
Due to file contents
```
apiVersion: kubeadm.k8s.io/v1beta1
caCertPath: /etc/kubernetes/pki/ca.crt
kind: JoinConfiguration
clusterName: @kubernetes_cluster_name
```

cluster name missing tag brackets in worker config

---

manifests/wait_for_default_sa.pp

Every run...
```
Notice: Kubernetes::Wait_for_default_sa[default]/Exec[wait for default serviceaccount creation in default]/returns: executed successfully
```

Avoid log message about waiting for SA when it already exists

---

manifests/config/worker.pp
spec/classes/config/worker_spec.rb

Add resource to manage creation of the /etc/kubernetes default config
directory for worker nodes to ensure that similar to the controller
node it is always created before attempting to write any managed
configuration files. Test that the directory is a requirement of the
configuration file, as it should be added via autorequires thus
ensuring correct ordering.
First time manifest apply on a worker node will fail due to the config
file not being able to be written as the directory '/etc/kubernetes'
does not exist.
Subsequent runs do complete as the directory is created by a side
effect of another process being executed. However this prevents stand
up from pristine from succeeding.

Add default k8s conf directory creation for worker

---

templates/v1beta1/config_worker.yaml.erb

tlsBootstrapToken was defined 2 times for worker nodes

Fixed duplicate tlsBootstrapToken in config_worker.yaml.erb for kubernetes 1.14

---

manifests/config/kubeadm.pp
spec/classes/config/kubeadm_spec.rb
templates/v1beta1/config_kubeadm.yaml.erb

Without setting the `controlPlaneEndpoint` workers don't get the right api endpoint to talk to in HA scenarios.

Manage the control plane endpoint

---

manifests/config/worker.pp

This config file contains sensitive data (the bootstrap token), so it should be hidden from logs.

set show_diff=>false on worker config

---

spec/classes/config/kubeadm_spec.rb
templates/v1beta1/config_kubeadm.yaml.erb

The v1beta1 package config should honor kubernetes_cluster_name

Support kubernetes_cluster_name in kubeadm 1.13+

---

README.md
manifests/config/kubeadm.pp
manifests/init.pp
spec/classes/config/kubeadm_spec.rb
spec/fixtures/hiera/required_values.yaml
templates/pki/front-proxy-ca.crt.erb
templates/pki/front-proxy-ca.key.erb
tooling/kube_tool.rb
tooling/kube_tool/create_certs.rb

This PR fixes the issue described in #275 by managing front-proxy-ca cert and key.
This means that metrics-server will work properly on a HA cluster deployed using the module.
The PR includes an update to the kube-tool docker container ruby code, therefore the kube-tool image on dockerhub should be updated accordingly.

Manage front-proxy ca certs - fixes #275

---

templates/v1beta1/config_worker.yaml.erb

Removed some keys that aren't used and moved tlsBootstrapToken to its correct position. 
Based change on https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1#JoinConfiguration

Fixed v1beta1 JoinConfiguration template to match the documentation

---

manifests/repos.pp

The kubernetes apt repository uses https and thus the defaults should reflect that.
Fixes: #334

Fix repository location for Ubuntu

---

README.md
spec/classes/config/kubeadm_spec.rb
templates/v1beta1/config_kubeadm.yaml.erb
templates/v1beta2/config_kubeadm.yaml.erb

This fixes https://github.com/puppetlabs/puppetlabs-kubernetes/issues/302 and https://github.com/puppetlabs/puppetlabs-kubernetes/issues/304.
Without this PR, the module cannot create functioning volume mounts into the control-plane pods. It is therefore not possible to, for example, mount an audit policy file or mount a directory to write audit logs to.

Add support for readOnly and pathType fields on volumes

---

tooling/Dockerfile
tooling/kube_tool/create_certs.rb

fixes log entries
```error “remote error: tls: bad certificate”, ServerName “”```
and adds all IPs for etcd servers to etcd server cert

Adding all IPs for etcd servers to etcd server cert

---

manifests/repos.pp

The kubernetes Debian repositories do not make use of codename-specific repositories. Instead a version for all supported releases is available in the "kubernetes-xenial" component. 
This change hardcodes this component name as the default accordingly. Of course this might break in the future, but since the value can be overriden via a parameter and this change makes the defaults work on a larger set of distributions (e.g. Ubuntu Bionic but probably also Debian) it seems to be a viable solution anyway.
Fixes: #335

Use correct apt release on Debian/Ubuntu

---

README.md

The logo in the readme refers to a file in the cncf/artwork repository.
Since these have been moved around the logo no longer shows up in the readme.
This fix pins the logo url to an exact commit.

Fix the certified-kubernetes-1.13 logo

---

manifests/init.pp
manifests/packages.pp
spec/classes/packages_spec.rb
templates/docker/daemon_debian.json.erb
templates/docker/daemon_redhat.json.erb

I had been customizing `/etc/docker/daemon.json` myself to inject registry mirrors and runtime config. This PR allows others to do the same without adding a bunch of individual params.

Add docker_extra_daemon_config for use when managing docker

---

manifests/config/kubeadm.pp
manifests/init.pp
spec/classes/config/kubeadm_spec.rb
templates/v1beta1/config_kubeadm.yaml.erb
templates/v1beta2/config_kubeadm.yaml.erb

This allows the ability to override the metricsBindAddress, which is currently hard coded to 127.0.0.1. This does not change the default, but allows it to be set.
Tommy

Allow setting metricsBindAddress

---

README.md
manifests/init.pp

Other than ```%{::ipaddress_eth1}``` there is a simpler way to specify the ip address that does not depend on the exact name of the networking interface: ```%{networking.ip}```
This pull requests simply updates the documentation to point users in this (simpler) direction.

Simplify the example for specifying ip addresses

---

tooling/kube_tool.rb
tooling/kube_tool/create_certs.rb

Currently, the client certificate that is created by the kubetool is shared between all controller nodes without any SAN (Subject Alternative Name). Checking etcd logs when the "master" etcd controller goes down show the following error:
`rejected connection from "10.10.10.104:43816" (error "remote error: tls: bad certificate", ServerName "")`
Because of that error, it's not possible anymore to call Kubernetes cluster using kubectl until the etcd node is back.
The fix implemented simply creates one client certificate per K8S controller node with SAN fields with correct values (DNS name and IP). After a few etcd failover tests, the etcd cluster continues to work and kubectl is working, too.
- Kubernetes version: 1.15.0
- etcd version: 3.4.3
- CentOS Linux release 7.6.1810 (Core)

Create client certificates per server with SAN values

---

manifests/init.pp

Seems like Etcd project has been moved from coreos to etcd-io: https://github.com/etcd-io/etcd/releases
Signed-off-by: Andrey Voronkov <avoronkov@enapter.com>

Update etcd repo from coreos to etcd-io

---

Rakefile
lib/puppet/parser/functions/kubeadm_join_flags.rb
manifests/cluster_roles.pp
manifests/config/kubeadm.pp
manifests/config/worker.pp
manifests/init.pp
manifests/packages.pp
spec/classes/cluster_roles_spec.rb
spec/classes/config/kubeadm_spec.rb
spec/classes/packages_spec.rb
spec/defines/kubeadm_init_spec.rb
spec/defines/kubeadm_join_spec.rb
templates/docker/daemon_debian.json.erb
templates/docker/daemon_redhat.json.erb
templates/etcd/etcd.erb
templates/etcd/etcd.service.erb
templates/v1alpha3/config_kubeadm.yaml.erb
templates/v1beta1/config_kubeadm.yaml.erb
templates/v1beta2/config_kubeadm.yaml.erb

This PR is the result of adapting the module to be used to replace a kubespray based deployment for a k8s 1.15.3 version.
The main relevant changes in the PR are the following:
* Add a `delegated_pki` option. If set to `true`, all the required x509 certificates under `/etc/kubernetes/pki/` must be provided externally by the module user by other means. We added that option as we are providing all certificates (including `sa.pub` and `sa.key`) from a Hashicorp Vault server dinamically instead of the ones generated by `kubetool`.
* Fix docker `daemon.json` templates. 
* Respect `docker_cgroup_driver` variable for `/etc/docker/daemon.json` generated file.
* Don't add extra `,` when `docker_storage_opts` is empty.
* Don't add extra `,` when `docker_extra_daemon_config` is an empty string
* …

Delegated PKI and adapt to k8s 1.15.3+

---

.github/workflows/release.yml
CHANGELOG.md
REFERENCE.md
manifests/init.pp
manifests/kube_addons.pp
manifests/packages.pp
metadata.json
spec/classes/packages_spec.rb
templates/docker_apt_package_pins.erb
templates/kubernetes_apt_package_pins.erb

- add option for package pinning on debian and ubuntu to prevent
accidential upgrades
- make dashboard installation more reliable
- simple reformatting to satisfy formatting rules
- adapt an enhance tests for the changes above
- add /usr/bin to default_path to solve #415
Sorry, i was not successful in executing the litmus tests described in the "Development" section on my ubuntu 18.04 system. "litmus:install_module" dropped very cryptic messages which were not understandable for a litmus newbie....
So probably you can fix potential acceptance test problems to get these useful changes to upstream?

improve initial installation

---

manifests/init.pp
manifests/kube_addons.pp
manifests/packages.pp
manifests/service.pp
spec/classes/packages_spec.rb
templates/docker_apt_package_pins.erb
templates/kubernetes_apt_package_pins.erb

This pull request adresses: #417 and #190.
Sorry, i was not successful in executing the litmus tests described in the "Development" section on my ubuntu 18.04 system. "litmus:install_module" dropped very cryptic messages which were not understandable for a litmus newbie.... (see #419)
So probably you can fix potential acceptance test problems to get these useful changes to upstream?

Package pinning and auto restart of etcd

---

README.md
manifests/config/kubeadm.pp
manifests/init.pp
templates/etcd/etcd.erb
templates/etcd/etcd.service.erb

In some setups the listening address and externally visible address can
be different. For instance in openstack setups with floating IPs, or
when using NAT. This change makes it possible to use different
addresses.

Implement advertise address for etcd

---

templates/v1beta1/config_kubeadm.yaml.erb
templates/v1beta2/config_kubeadm.yaml.erb

Commit to remove applies to  Kubernetes 1.16.0+
https://github.com/kubernetes/kubernetes/commit/eee3e976d871bcbf97821a0fa9c129a4c568ac5e
Error with this config deployed on 1.17.2:
```
W1105 15:55:06.751793   19570 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "resourceContainer"
```

Remove invalid kube-proxy config resourceContainer

---

manifests/config/kubeadm.pp
manifests/init.pp
spec/classes/config/kubeadm_spec.rb
templates/v1beta1/config_kubeadm.yaml.erb
templates/v1beta2/config_kubeadm.yaml.erb

This PR adds support for configuring conntrack settings in kubeadm config.yaml file.

Add configuration options for conntrack settings in v1beta1 and v1beta2

---

metadata.json
provision.yaml

Remove RedHat support because Docker and RedHat are no longer officially a supported combination.
See: docker/docker-install#190

IAC-1246 - Remove RedHat support

---

README.md
manifests/config/kubeadm.pp
manifests/init.pp
spec/classes/config/kubeadm_spec.rb
templates/v1beta1/config_kubeadm.yaml.erb
templates/v1beta2/config_kubeadm.yaml.erb

Upstream docs: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#scheduler-flags
Appears valid as far back as docs go that I could find: https://v1-15.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#scheduler-flags
One example of how I am going to use this:
```yaml
kubernetes::scheduler_extra_arguments:
- 'bind-address: 0.0.0.0'
```

Add scheduler_extra_arguments parameter

---

README.md
manifests/init.pp
manifests/packages.pp
manifests/repos.pp
manifests/service.pp
spec/classes/packages_spec.rb
spec/classes/repos_spec.rb
templates/containerd/config.toml.erb
templates/containerd_apt_package_pins.erb
templates/docker_apt_package_pins.erb

To maintain backwards compatibility I made the package install of containerd opt-in via a parameter. If it would be preferred I can make the package install method the only way to install containerd.
Docs: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
One motivation behind this is being able to use Puppet to pin package versions, where the archive approach doesn't lend itself to upgrades via Puppet without deleting something like `/usr/bin/runc` or `/usr/bin/containerd` and re-running Puppet.  Also Kubernetes 1.20 future release will deprecate Docker as container runtime so felt it would be good to improve on the containerd install method.
Also noticed a bug where the docker apt pinning was pinning kubernetes packages and the kubernetes apt pinning …

Support installing containerd using a package

---

manifests/init.pp
manifests/packages.pp
spec/classes/packages_spec.rb

Using `/var/tmp` on systems, at least in my case, results in the directory getting purged by systemd tmp space cleanup and so after a few weeks Puppet has to add the directory back which is not ideal and state changes that are unnecessary.

Allow tmp_directory to be changed

---

README.md
REFERENCE.md
manifests/init.pp
spec/defines/kubeadm_init_spec.rb
spec/spec_helper_acceptance_local.rb
tasks/swagger_k8s_get_api_versions.json

Removal of any offensive or inappropriate terminology from the code base.
References towards `node-role.kubernetes.io/master-` and `kubernetes::taint_master` have been left as I am unsure if they can/should be removed.

(IAC-995) - Removal of Inappropriate Terminology

---

README.md
manifests/init.pp
manifests/kube_addons.pp
spec/classes/kube_addons_spec.rb
tooling/kube_tool.rb
tooling/kube_tool/other_params.rb

Resolves #469
Recent releases of Calico (>=3.15) seem to prefer being installed with the Tigera operator.  This commit handles that.
cni_pod_cidr is also injected into the Installation object, as Calico and Tigera seem to ignore the networking.podSubnet set within the kubeadm-config ConfigMap.

Fix calico CNI support

---

templates/v1alpha3/config_kubeadm.yaml.erb
templates/v1alpha3/config_worker.yaml.erb
templates/v1beta1/config_kubeadm.yaml.erb
templates/v1beta1/config_worker.yaml.erb
templates/v1beta2/config_kubeadm.yaml.erb
templates/v1beta2/config_worker.yaml.erb

With Kubernetes 1.19.4 this is message I get when I restart kubelet:
```
Jan 21 14:37:33 kubecontroller-dev kubelet: W0121 14:37:33.169859   53934 util_unix.go:103] Using "/run/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///run/containerd/containerd.sock".
```

Update criSocket to avoid deprecation warnings

---

README.md

I was specifying `1.20` and I was getting this error.
```
kubeadm init --config '/etc/kubernetes/config.yaml' --ignore-preflight-errors='Service-Docker,' --v=5
I0223 17:24:54.964143   20131 initconfiguration.go:201] loading configuration from "/etc/kubernetes/config.yaml"
version "v1.20" doesn't match patterns for neither semantic version nor labels (stable, latest, ...)
```
Took me a while to figure out what was wrong. 
This PR improves the docs in that regard,

Add note about the kubernetes version format

---

.github/workflows/integration_test.yml
.github/workflows/nightly.yml
plans/provision_cluster.pp
plans/puppetserver_setup.pp
spec/acceptance/integration_kubernetes_spec.rb

Add parameters to accept different provisioning type
By adding this parameter will help to test on gcp/abs etc
Modifies tests to match spaces in output
Modified workflows to remove reference to non-puppetlabs repo
Modified puppet server plans wrt the new changes
Modified plans to accommodate the inventory file location
ABS Results
`Running acceptance test on woolen-chimney with address woolen-chimney.delivery.puppetlabs.net and OS centos-7-x86_64
we are able to setup a controller and workers
set up the controller
set up controller
sets up the controller
set up the worker1
set up worker
sets up the worker
set up the worker2
set up worker
sets up the worker
verify the k8 nodes
verify the k8 nodes
verify the k8 nodes
the Kubernetes module
clean up before each test
kubernetes class
it should …

(maint) add parameters to accept different provisioning type

---

manifests/packages.pp

Fix https://github.com/puppetlabs/puppetlabs-kubernetes/issues/515

Add config.toml for containerd installed with 'archive'

---

REFERENCE.md
manifests/init.pp
manifests/wait_for_default_sa.pp

The currently hardcoded parameters for the number of tries and sleep duration work for most setups. However, in some slower environments (like Vagrant), 30 sec is not enough to create a service account.
This change allows configuring `$wait_for_default_sa_tries` and `$wait_for_default_sa_try_sleep` so that they could be adjusted to a particular situation if needed.

Allow configuring of waiting times during sa creation

---

README.md
manifests/kube_addons.pp
spec/classes/kube_addons_spec.rb
tooling/kube_tool.rb
tooling/kube_tool/other_params.rb

#473 is not the right way to install Calico since the previous deployment method before that change was to deploy the on-premise YAML which installs the daemon sets to `kube-system` namespace which is still valid with all recent versions: https://docs.projectcalico.org/getting-started/kubernetes/self-managed-onprem/onpremises.
The Tigera install is documented as the "quickstart" method: https://docs.projectcalico.org/getting-started/kubernetes/quickstart but is not where close to what used to be previous behavior of this module.
If this solution of changing to using `calico-tigera` is not preferred let me know and I can adjust maybe to make the namespace dynamic.  But the whole idea of modifying a file line from YAML is 100% not needed for on premise deployments of Calico which is the …

Support both standard Calico and Calico Tigera

---

README.md
manifests/init.pp

Finally, runc v1.0.0 was released 20 days ago. https://github.com/opencontainers/runc/releases/tag/v1.0.0
This module should default to runc stable version instead of the RC.

Change default runc version to 1.0.0

---

manifests/init.pp
manifests/kube_addons.pp
spec/classes/kube_addons_spec.rb

Fix for https://github.com/puppetlabs/puppetlabs-kubernetes/issues/421
The URL changed after v2.0.0 this is why it was not working.
This patch is backwards compatible in case someone still wants to use old versions of the dashboard.
Thanks.

Support for kubernetes dashboard version 2.0.0 and onwards

---

templates/docker/daemon_debian.json.erb
templates/docker/daemon_redhat.json.erb

The live restore option helps reduce container downtime due to daemon crashes, planned outages, or upgrades. By default, when the Docker daemon terminates, it shuts down running containers. This option allows to keep all containers running.

Enable live-restore for Docker daemon.

---

.fixtures.yml
metadata.json

(GH-iac-334) Remove Support for Ubuntu 16.04
pdk version: `2.1.0`

pdksync - (GH-iac-334) Remove Support for Ubuntu 16.04

---

spec/classes/config/kubeadm_spec.rb
templates/v1beta2/config_kubeadm.yaml.erb
templates/v1beta2/config_worker.yaml.erb
templates/v1beta3/config_kubeadm.yaml.erb
templates/v1beta3/config_worker.yaml.erb

This is the warning with Kubernetes 1.22.4:
```
kubelet: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
```

Remove cgroup-driver arg to avoid deprecation warnings

---

README.md
manifests/init.pp
manifests/packages.pp
manifests/service.pp
spec/classes/packages_spec.rb
spec/classes/repos_spec.rb
spec/classes/service_spec.rb
templates/http-proxy.conf.erb

This PR adds the ability to configure proxying for the container runtime and Kubelet.
Add 3 new string variables - http_proxy, https_proxy and no_proxy.
[*http_proxy*]
Configure the HTTP_PROXY environment variable
[*https_proxy*]
Configure the HTTPS_PROXY environment variable
[*no_proxy*]
Configure the NO_PROXY environment variable
Add a boolean 'container_runtime_use_proxy' which when set to true will cause
the new proxy variables to be applied to the container runtime.
[*container_runtime_use_proxy*]
Configure whether the container runtime should be configured to use a proxy.
If set to true, the container runtime will use the http_proxy, https_proxy and
no_proxy values.
Add a boolean 'kubelet_use_proxy' which when set to true will cause the
http_proxy, https_proxy and no_proxy variables …

Add proxy support to docker, cri_containerd and kubelet

---

data/os/Debian/11.yaml
metadata.json
spec/classes/packages_spec.rb
templates/containerd/config.toml.erb

On Debian 11 the [recommended cgroups driver](https://github.com/containerd/containerd/blob/main/docs/cri/config.md) is `systemd` however the `systemdCgroups` parameter is required otherwise one will encounter [weird issues](https://github.com/kubernetes/website/issues/33795).

Support Debian 11

---

manifests/config/kubeadm.pp
spec/classes/config/kubeadm_spec.rb
templates/v1beta2/config_kubeadm.yaml.erb

`master` role [has been deprecated](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#urgent-upgrade-notes):
> Introduce a new label "node-role.kubernetes.io/control-plane" that will be applied in parallel to "node-role.kubernetes.io/master" until the removal of the "node-role.kubernetes.io/master" label.

Master role has been deprecated since kubernetes v1.20.0

---

manifests/config/kubeadm.pp
manifests/kubeadm_init.pp
manifests/kubeadm_join.pp
manifests/service.pp
spec/classes/config/kubeadm_spec.rb

Removed incorrect functionality and test cases.
Added spec test to ensure that ETCD_DATA_DIR exists in the config file generated and ensures the default value of etcd_data_dir is its value
Additional tests will come with CONT-215

(CONT-217) Correct Kubernetes etcd_data_dir spec tests

---

metadata.json
spec/classes/init_spec.rb

This PR refactor spec so that at least the basic tests executed for each supported OS family.
This might catch in the future some basic errors when `metadata.json` is changed.
Goolge's YUM repos currently doesn't support newer RedHat releases. Though at least RedHat 7 is definitely supported.

Add RedHat family as supported OS (#563)

---

templates/containerd/config.toml.erb

Adjusts the `containerd` configuration to properly address the `containerd` socket via URI; fixes deprecation warnings when using `crictl` on nodes.

Switch containerd grpc socket to URI

---

tooling/Dockerfile

Fix Build docker image tooling
Now, the build of the image is broken https://github.com/puppetlabs/puppetlabs-kubernetes/actions/runs/3406639576/jobs/5665490029#step:15:31
I'm making a docker image build fix
Prior to this commit, testing could not be executed due to docker failures. 
This commit resolves the docker failures and allows the tests to proceed.

Fix Build docker image tooling

---

manifests/kube_addons.pp
manifests/kubeadm_init.pp
manifests/kubeadm_join.pp
manifests/packages.pp
manifests/wait_for_default_sa.pp
metadata.json

Prior to this commit, an issue arised for Kubernetes that confirmed some code regressions within the module after the Codebase Hardening update (CONT-8). After investigating the resulting regression, some errors in the sanitisation process were spotted.
This PR aims to address these errors produced during the hardening stage before properly investigating and addressing the current regression (CONT-272).
Note: This PR will initially be categorised as maintenance. However, it might be related to both CONT-272 / #585 and CONT-263.

(MAINT) Fixing codebase hardening issues

---

README.md
manifests/init.pp
manifests/packages.pp
spec/classes/packages_spec.rb
templates/containerd/config.toml.erb

This commits reverts changes done in cfbd9de13d52cf260b1776f005ef91125d8263d0  (#576) while allowing overriding socket path via `kubernetes::containerd_socket` parameter.
The address `unix:///run/containerd/containerd.sock` doesn't seem to be supported by all `containerd` versions.
cc @chelnak 
Fixes #596.

Support overriding containerd socket path (#596)

---

manifests/kube_addons.pp
spec/classes/kube_addons_spec.rb

This PR attempts to fix some changes introduced in #592 and #575.
- Wrap commands in single array
- Don't use double quotes for strings where string interpolation isn't needed
- Avoid unnecessary code duplication
The exec containing `command` in form 
```
['kubectl', 'get', 'nodes']
```
will print help message to stdout instead of executing `kubectl get nodes`.

Fix executing CNI addons commands (fixes #594)

---

manifests/cluster_roles.pp
manifests/config/kubeadm.pp
manifests/config/worker.pp
manifests/init.pp
manifests/kube_addons.pp
manifests/kubeadm_init.pp
manifests/kubeadm_join.pp
metadata.json
spec/classes/init_spec.rb

Do not allow any arbitrary string to be passed as node_name, as the variable is frequently passed to shell scripts.
The hardening efforts #575, #592 attempts to prevent code injection also via `node_name` variable. However it broke some functionality (#594).
This PR adds type checking for `kubernetes::node_name` using [Stdlib:Fqdn](https://github.com/puppetlabs/puppetlabs-stdlib/commit/127b2f9b36b6f41a62db0d68f3908e7c227871a0) that was introduced in `puppetlabs-stdlib` in version `4.25.0`. 
Currently there's a [similar type check](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/main/manifests/kube_addons.pp#L93) only in `kube_addons.pp` class
```
/^[a-zA-Z0-9]([a-zA-Z0-9\-\.]{0,251}[a-zA-Z0-9])?$/
```
the `stdlib::fqdn` pattern looks like this:
``` …
```

Stronger type checking for $node_name

---

manifests/kube_addons.pp
manifests/kubeadm_init.pp
manifests/kubeadm_join.pp
manifests/packages.pp
manifests/service.pp
manifests/wait_for_default_sa.pp
spec/classes/kube_addons_spec.rb
spec/defines/kubeadm_init_spec.rb
spec/defines/kubeadm_join_spec.rb
spec/defines/wait_for_default_sa_spec.rb

This PR cleans up a few discrepancies left over from the hardening work.
Along with the work from @deric , the work here should help towards returning main back to a green state.

(MAINT) Revert hardening changes

---

manifests/wait_for_default_sa.pp
spec/defines/wait_for_default_sa_spec.rb
types/namespace.pp

[Namespace naming](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) should conform to DNS subdomain name as defined in [RFC 1035](https://www.rfc-editor.org/rfc/rfc1035) and [RFC 1123](https://tools.ietf.org/html/rfc1123):
- contain at most 63 characters
- contain only lowercase alphanumeric characters or '-'
- start with an alphanumeric character
- end with an alphanumeric character
When enforcing such policy code injection should not be possible (no need to escape namespace name).

Validate namespace parameter as DNS subdomain name

---

tooling/Dockerfile
tooling/kube_tool.rb
tooling/kube_tool/clean_up.rb
tooling/kube_tool/create_certs.rb
tooling/kube_tool/other_params.rb
tooling/start-kubetool.sh

Use less code to do the same thing. Arguments are defined in one place and can be read from `ENV` without using bash script to translate ARGS.
- Upgraded Ruby base image
- Fixed insecure CA algorithm
- Short options remained the same:
```
usage: /etc/k8s/kube_tool.rb [options]
-o, --os                    The OS that Kubernetes will run on
-v, --version               The Kubernetes version to install
-r, --container_runtime     The container runtime to use. This can only be "docker" or "cri_containerd"
-c, --cni_provider          The networking provider to use, flannel, weave, calico, calico-tigera or cilium are supported
-p, --cni_provider_version  The networking provider version to use, calico and cilium will use this to reference the correct deployment download link
-t, --etcd_ip …
```

Rewrite command line arguments parsing

---

metadata.json

bumping puppetlabs-apt dependency version requirement from <9.0.0 to <10.0.0.

(maint) - Bump dependencies before major release 

---

metadata.json

the use of herculesteam-augeasproviders_core has been deprecated and should be replaced with puppet-augeasproviders_core.

(MAINT) -  update-deprecated-dependency

---

tooling/Dockerfile
tooling/Makefile

Pinpoint to exact version of cfssl and stable golang version. While trust stored (trusted certificates) should be used at latest version.
After upgrading to golang 1.18+ it's possible to use `go install` instead of cloning whole repo.

Reproducible kube-tool build

---

manifests/repos.pp

On Debian based distributions following error might appear, due to outdated GPG key:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
W: Failed to fetch https://apt.kubernetes.io/dists/kubernetes-xenial/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
As a workaround the default value can be overrided in Hiera config:
```yaml …
```

Update GPG fingerprint for apt.kubernetes.io

---

metadata.json
spec/acceptance/integration_kubernetes_spec.rb
spec/acceptance/kubernetes_spec.rb
spec/spec_helper_acceptance_local.rb
tooling/kube_tool/create_certs.rb
tooling/kube_tool/other_params.rb

Summary of changes:
1. Updated deprecated `herculesteam-augeasproviders_sysctl` to `puppet-augeasproviders_sysctl` to resolve dependency cycle on `install module` step
2. Pointed towards static cni-provider [weave-demonset-k8s-1.11.yaml](https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s-1.11.yaml), (as per suggested comment [here](https://github.com/weaveworks/weave/issues/3960#issuecomment-1266694062) from weave) after [cloud.weave.works](http://cloud.weave.works/) was taken out of service.
3. Updated legacy fact `$::ipaddress` to use the already present`fetch_ip_by_hostname` method in `spec_helper_acceptance_local.rb` as GCP VMs include both an internal/external IP address which caused issues.
4. Updated test manifest in …

(CONT-914) - Address CI Failures

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

Prior to this commit, there were deprecation warnings in the k8s CI. This is because K8s was using checkout@v2 rather than v3. This commit adds v3.

(CONT-903) Use checkout@v3 in Kubernetes

---

README.md
REFERENCE.md
manifests/init.pp
templates/0-containerd.conf.erb
templates/v1beta3/config_kubeadm.yaml.erb
tooling/kube_tool/other_params.rb

This was tested on Debian bookworm with kubernetes version 1.26 and 1.27, calico v3.25
UdpIdleTimeout has been deprecated:
- https://github.com/kubernetes-sigs/kubespray/pull/9925/files
- https://github.com/kubernetes/kubernetes/pull/112133/files
Kubernetes has moved the registry to:
- registry.k8s.io
Reference as seen in the red banner on their website:
- https://kubernetes.io/
Calico requires a `v` before the version number without it you get a 404 Example:
- https://docs.projectcalico.org/archive/v3.18/manifests/calico.yaml
- https://docs.projectcalico.org/archive/3.18/manifests/calico.yaml
container-runtime remote has been deprecated as the only possible value was remote
- Reference: https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
Error i received:
```
Apr …
```

General fixes

---

REFERENCE.md
manifests/config/kubeadm.pp
manifests/config/worker.pp
manifests/init.pp
manifests/packages.pp
spec/acceptance/kubernetes_spec.rb
spec/spec_helper_acceptance_local.rb

As per prior discussion within this PR I've made systemd the default cgroup_driver for the next major release or when ready.
https://github.com/puppetlabs/puppetlabs-kubernetes/pull/625
https://github.com/puppetlabs/puppetlabs-kubernetes/pull/625#issuecomment-1551496610
TLDR;
The default cgroup_driver for kubelet is systemd, however the default within this module for containerd is set to cgroupfs which causes a conflict between containerd & kubelet leading to kubelet crashlooping. This PR is to set the default cgroup_driver for containerd to systemd as recommended by the kubernetes team [Kubernetes Docs for this](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/)
Tested on Debian bullseye & bookworm.
There are still a few files which have this set to …

Make cgroup_driver default to systemd

---

README.md
manifests/kube_addons.pp
spec/classes/kube_addons_spec.rb
tooling/kube_tool/other_params.rb

Flannel CNI is installed into `kube-flannel` namespace, not `kube-system`, see e.g. [kube-flannel.yml](https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml)
This PR fixes a corrective flannel installation that is repeated on each puppet run, when `flannel` CNI is used.

Fix flannel install condition

---

spec/default_facts.yml
spec/spec_helper.rb

Fixing the spec failure caused while removing legacy spec with updated one.
- Replacing [legacy facts](https://github.com/puppetlabs/puppetlabs-kubernetes/pull/645) with updated caused spec failure.
Mention any related issues or pull requests.

(MAINT) - Update default fact with hostname

---

spec/classes/config/kubeadm_spec.rb
templates/v1beta3/config_kubeadm.yaml.erb

The v1beta3 template needs to use correct argument to get the scheduler extra args.
I upgraded from 6.0.0 to 8.0.0 and lost some changes:
```diff
scheduler:
-  extraArgs:
-    bind-address: 0.0.0.0
```
The Hiera I have is this:
```yaml
kubernetes::scheduler_extra_arguments:
- 'bind-address: 0.0.0.0'
```
Mention any related issues or pull requests.

Ensure correct scheduler extra arguments passed to v1beta3 template

---

.devcontainer/README.md
.devcontainer/devcontainer.json
.vscode/extensions.json

* The devcontainer spec changed to put vscode-specific settings under `customizations.vscode` 
* The rebornix Ruby extension was deprecated, with a recommendation to use the Ruby LSP extension instead
* Replace tabs in JSON with spaces
* devcontainers/spec#1
* rubyide/vscode-ruby#dc81c809c82003d26af9c4dc7c89fa8f8a26cbf5
- [X ] Manually verified. (For example `puppet apply`)

Update devcontainer format + Ruby vscode extension

---

Gemfile

(CAT-1256) Roll out puppetlabs-puppet-lint and puppetlabs-rspec-puppet through spec_helper v7.0
pdk version: `3.0.0`

pdksync - (CAT-1256) Roll out puppetlabs-puppet-lint and puppetlabs-rspec-puppet through spec_helper v7.0

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
Gemfile
manifests/config/kubeadm.pp
manifests/config/worker.pp
manifests/init.pp
manifests/repos.pp
metadata.json
spec/acceptance/integration_kubernetes_spec.rb
spec/acceptance/kubernetes_spec.rb
spec/spec_helper_acceptance_local.rb

Fixed puppetlabs-kubernetes modules CI & nightly failures
1. replaced CENTOS-7 with RHEL-8
2. Updated test as per new changes
3. Fixed version for `puppet-modulebuilder` gem, as newer version of this gem does not include `tooling` folder. We will keep this until we find a solution to either move the `tooling` folder in to some other folder or get rid of it altogether.

(CAT-2095): Fixed puppetlabs-kubernetes modules CI & nightly failures

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
data/os/debian.yaml
data/os/rhel.yaml
manifests/init.pp
manifests/repos.pp
spec/acceptance/kubernetes_spec.rb
spec/classes/config/kubeadm_spec.rb
spec/classes/init_spec.rb
spec/classes/repos_spec.rb
spec/spec_helper_acceptance_local.rb

Fixed kubernetes environment setup for Debian. This allows spec tests to run successfully for debian platform

(CAT-2193): Fixed kubernetes environment setup for Debian.

---

metadata.json

Updated the version for puppetlabs-apt module in metadata.json file.
After a new release of puppetlabs-apt to 10.0.1, broke the dependency check in puppetlabs-kubernetes. This change will fix the dependency issue.

(MAINT): Updated the version for puppetlabs-apt module in metadata.json file

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
metadata.json

Adds the Twingate installation step in `.github/workflows/...` using `twingate/github-action@v1`. The action uses the `${{ secrets.TWINGATE_KEY }}` to establish secure access to internal resources.
This enables the workflow to access protected infrastructure during CI runs.

ci(MODULES-11557): add Twingate setup step to GitHub Actions workflow
